### ISSUE TITLE
Support large files

### ISSUE THREAD

**Issue by yannschepens** [winnfsd/winnfsd#6]

**Comment by SirWaddles** [comment]
The SCP error I get is just

    SCP did not finish successfully

and the only NFS operation that shows up in the log when it failed was an MKDIR on a directory which already exists.

Since it doesn't even get to the WRITE operation, I think this may be unrelated to filesize, and perhaps even related to the issue in the other page, as I discovered that running an ls in the directory where the file is supposed to be written actually allows SCP to finish properly.

**Comment by yannschepens** [comment]
Ok, I close this issue and go back to the other one
