### ISSUE TITLE
UNSTABLE storage

### ISSUE THREAD

**Issue by SirWaddles** [winnfsd/winnfsd#9]
NFSv3 WRITE will always return FILE_SYNC even if given UNSTABLE as an option.

I think this will slow down writing to disk by a huge amount as the current implementation will open a file, write the buffer and close the file on potentially thousands of NFS write calls.

I'm working on an implementation of the UNSTABLE method along with an NFS COMMIT procedure.

Just as a side note, are there any sort of design standards regarding this project? It seems like it has some C-style origins that are adhered to only sporadically. I ask because I've used stuff like std::vector and std::string in the UNSTABLE storage branch and I'm not sure if it's appropriate.

**Comment by marcharding** [comment]
Hey, are you still working on this? If not, can you share the code you have so far?

**Comment by SirWaddles** [comment]
I'd stopped working on this because the project seemed kind of dead. I don't think you'd want the code I had, it didn't really work at all. I was just trying a few things to keep the storage in memory, but I was having issues with how some of the padding worked.

You can see [my commit](https://github.com/SirWaddles/winnfsd/commit/c0703cab1cae2b3fef043b1932fd20c97bd44264) if you did want to see my approach, but if I was going to continue this I'd probably start again anyway.

**Comment by marcharding** [comment]
Thanks! I took you approach and simplified it. The map/vector approach was slower than a normal write in my tests and fills up ram. 

See https://github.com/marcharding/winnfsd/commit/41054bb30f94f72121ad853007b89a727c2be00a for my approach.

Its a bit hacky but this and the increased send/receive buffer results in write speeds > 100MB/s (when using the virtio adapter).

I'm open for suggestions, especially since offset and count are not implemented in COMMIT (i have no clue if its possible this way).

**Comment by marcharding** [comment]
Implemented in 2.2.0.
